# Generated by Django 5.1.1 on 2024-09-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
    ]
